### ISSUE TITLE
Anti-aliasing: Enable Access to Renderer

### ISSUE THREAD

**Issue by YosanAI** [googlemaps/js-three#209]
I want access to the renderer so that I can enable antialiasing and other options that can be passed to `THREE.WebGLRenderer`

`renderer = new THREE.WebGLRenderer( { antialias: true} );`

[this](https://threejsfundamentals.org/threejs/lessons/threejs-multiple-scenes.html) resource mentions that "WebGL resources can not be shared across contexts", which will force us to upload assets twice if we want to clone the scene to another canvas. However, if we have access to the renderer, we can use the workaround mentioned on the linked resource.

**Comment by usefulthink** [comment]
Even with access to the renderer this would not work, since it is the google maps API that creates the rendering-context and passes it on to the overlay view. 

As far as I know, antialiasing is disabled in the google maps renderer for performance reasons, they internally rely on other methods to do antialiasing, likely similar to those described [in this article](https://blog.mapbox.com/drawing-antialiased-lines-with-opengl-8766f34192dc).

That said, there is no way to enable that externally (except maybe for hacks where you intercept google maps' call to `HTMLCanvasElement.createContext()` and overwrite their antialias setting, but that will lead to at least some performance degradation and maybe worse).

The resource you linked is also right that you normally shouldn't be doing this, but in the case of the integration between three.js and the maps renderer, great care was taken to save and restore the webgl-state to make this work.
