### ISSUE TITLE
Ability to combine WebGLOverlayView with other libraries

### ISSUE THREAD

**Issue by crunchwrap89** [googlemaps/js-three#437]
**Is your feature request related to a problem? Please describe.**
I am using map.data.loadGeoJson() to set border colors and fillColors to specific countries and cities.
I am also using the googlemaps/three package to add 3D objects to the map. However when i add 3D Objects i would like the 3D objects to be placed on a higher zIndex than the borderColor and fillColor from the google.maps.Data.StyleOptions.

Currently the 3D objects will be placed on a lower zIndex so the objects will be placed below the borderColor and fillColor.

I have tried to control this with the zIndex parameter in "google.maps.Data.StyleOptions" without success.

 **Describe the solution you'd like**
I would like to control the zIndex of the gl.canvas within ThreeJSOverlayView so that i can place layers of other libraries such as the drawing library, visualization library and google.maps.Data.StyleOptions below the ThreeJSOverlay.

 **Additional context**
To reproduce the issue and play around with other libraries combined with googlemaps/three, follow instructions of readme.md in below repo.
https://github.com/crunchwrap89/googlemaps-three-zIndex

![screenshot](https://user-images.githubusercontent.com/19464526/173024155-3373f422-cbfe-4333-905b-37d4ea73a8ee.png)

**Comment by amuramoto** [comment]
This is expected behavior. Objects rendered in WebGLOverlayView are rendered on the basemap layer, and DataLayer is actually a separate layer overlaid on the basemap, so there's no way to affect the stacking order between the two with z-index (admittedly this is confusing because 'OverlayView' is somewhat of a misnomer in the naming of WebGLOverlayView). 

You would need to render your GeoJSON with WebGLOverlayView manually or using something like [GeoJsonLayer](https://deck.gl/docs/api-reference/layers/geojson-layer) in deck.gl
