### ISSUE TITLE
polyline over 3d object

### ISSUE THREAD

**Issue by dognk** [googlemaps/js-three#529]
#### Environment details

javascript, google maps, threejs 

#### Steps to reproduce

  1. i draw a polyline with google maps and put the 3d objects whit threejs but the line draw over the 3d object  

# example

![ejemplo](https://user-images.githubusercontent.com/6304322/194913787-b39ff3a5-6027-451d-9589-194b57676b79.png)

Following these steps will guarantee the quickest resolution possible.

Thanks!

**Comment by amuramoto** [comment]
This is expected behavior. What's happening is that the 3D object is rendered directly as part of the basemap, but polylines are actually rendered in a separate overly on the map. The only way to achieve the effect you are looking for would be to also draw the polyline using ThreeJS (or WebGL directly or some other WebGL library). Then you could control the stacking order.
